POST http://smarthumanlife.herokuapp.com:8787/login
Content-Type: application/json

{
  "username": "nalsme98",
  "password": "1234"
}

###

POST http://smarthumanlife.herokuapp.com:8787/signup
Content-Type: application/json

{
  "username": "nalsm98",
  "password": "1234",
  "birthday": "1998.05.18",
  "department": "정보통신공학과",
  "phone": "010-7188-9608",
  "email": "nalsm0518@gmail.com",
  "introduction": "안녕하세요!"
}

###